const WebProjectsData = [
  {
    project_id: 1,
    name: "Shwe Mingalar Spa",
    type: "Spa",
    language: "WordPress",
    link: "https://www.shwemingalarspa.com/shwemingalarspa.com",
    buttonText: "Visit",
  },
  {
    project_id: 2,
    name: "Kathit Htoo",
    type: "Trading",
    language: "WordPress",
    link: "https://www.kthmm.com/",
    buttonText: "Visit",
  },
  {
    project_id: 3,
    name: "Thanlwin Technic Aviatin Services",
    type: "Aircraft Cleaning",
    language: "WordPress",
    link: "https://www.ttas-mm.com/",
    buttonText: "Visit",
  },
  {
    project_id: 4,
    name: "Min Myanmar Search",
    type: "Research",
    language: "WordPress",
    link: "https://www.minmyanmarrs.com/",
    buttonText: "Visit",
  },
  {
    project_id: 5,
    name: "JandM Steel Solutions",
    type: "Construction",
    language: "WordPress",
    link: "https://www.jandmss.com/",
    buttonText: "Visit",
  },
  {
    project_id: 6,
    name: "Myanmar Barcode Association",
    type: "Barcode",
    language: "PHP, WordPress",
    link: "https://www.gs1mm.org/",
    buttonText: "Visit",
  },
  {
    project_id: 7,
    name: "Sweet Home",
    type: "Construction",
    language: "WordPress",
    link: "https://www.sweethomemm.com/",
    buttonText: "Visit",
  },
  {
    project_id: 8,
    name: "Ministry of Sports and Youth Affairs",
    type: "Sports",
    language: "WordPress",
    link: "https://www.mosya.gov.mm/",
    buttonText: "Visit",
  },
  {
    project_id: 9,
    name: "Peace Myanmar Electric Holding",
    type: "Mistubishi Electronic Products",
    language: "WordPress",
    link: "https://www.onlineshop.pmeholding.com/",
    buttonText: "Visit",
  },
  {
    project_id: 10,
    name: "OMI Marine",
    type: "Crew and Ship Management",
    language: "WordPress",
    link: "https://www.omimarine.com/",
    buttonText: "Visit",
  },
  {
    project_id: 11,
    name: "Golden Bulk Marine",
    type: "Crew and Ship Management",
    language: "WordPress",
    link: "https://www.goldenbulkmarine.com/",
    buttonText: "Visit",
  },
  {
    project_id: 12,
    name: "2B Great",
    type: "Logistics & Freight",
    language: "WordPress",
    link: "https://www.2bgreat-tha-mm.com/",
    buttonText: "Visit",
  },
  {
    project_id: 13,
    name: "Athena Inspiration Groups",
    type: "Online Shopping",
    language: "WordPress",
    link: "https://www.athenainspirationgroup.com/",
    buttonText: "Visit",
  },
  {
    project_id: 14,
    name: "Table Music",
    type: "Music",
    language: "WordPress",
    link: "https://www.tablemusic.com/",
    buttonText: "Visit",
  },
  {
    project_id: 15,
    name: "Millcon Thiha",
    type: "Construction",
    language: "WordPress",
    link: "https://www.millconthiha.com/",
    buttonText: "Visit",
  },
  {
    project_id: 16,
    name: "S ONE",
    type: "Auto Spare Parts & Services",
    language: "WordPress",
    link: "https://www.soneauto.com/",
    buttonText: "Visit",
  },
  {
    project_id: 17,
    name: "Orient Bright Yangon",
    type: "Certificate",
    language: "WordPress",
    link: "https://www.oreintbrightygn.com/",
    buttonText: "Visit",
  },
  {
    project_id: 18,
    name: "M9 Sports",
    type: "Sports News",
    language: "WordPress",
    link: "https://www.m9sports7.com/",
    buttonText: "Visit",
  },
  {
    project_id: 19,
    name: "West Yangon Technological University",
    type: "Technological University",
    language: "Laravel",
    link: "https://www.wytu.edu.mm/",
    buttonText: "Visit",
  },
  {
    project_id: 20,
    name: "Safety Life Myanmar Security",
    type: "Security",
    language: "WordPress",
    link: "https://www.safetymyanmarsecurity.com/",
    buttonText: "Visit",
  },

  {
    project_id: 21,
    name: "One Two One Group",
    type: "Trading",
    language: "WordPress",
    link: "https://www.onetwoonegroup.com/",
    buttonText: "Visit",
  },
  {
    project_id: 22,
    name: "Family Private School Hinthada",
    type: "Private School",
    language: "WordPress",
    link: "https://www.familyprivateschoolhinthada.com/",
    buttonText: "Visit",
  },
  {
    project_id: 23,
    name: "Kingdom Myanmar",
    type: "Plastic Bag & Packaging",
    language: "WordPress",
    link: "https://www.kingdommyanmar.com/",
    buttonText: "Visit",
  },
  {
    project_id: 24,
    name: "Sky Golden Bridge",
    type: "IT Services",
    language: "WordPress",
    link: "https://www.skygoldenbridge.com/",
    buttonText: "Visit",
  },
  {
    project_id: 25,
    name: "Concept 51 Furniture",
    type: "Furniture",
    language: "WordPress",
    link: "https://www.concept51furniture.com/",
    buttonText: "Visit",
  },
  {
    project_id: 26,
    name: "Myanmar Yijin",
    type: "Construction",
    language: "WordPress",
    link: "https://www.myanmaryijin.com/",
    buttonText: "Visit",
  },
  {
    project_id: 27,
    name: "Ocean Majesty",
    type: "Ship Crew Management",
    language: "WordPress",
    link: "https://www.oceanmajesty.com/",
    buttonText: "Visit",
  },
  {
    project_id: 28,
    name: "Nawarat Myay",
    type: "Agrochemical Products",
    language: "WordPress",
    link: "https://www.nawaratmyay.com/",
    buttonText: "Visit",
  },
  {
    project_id: 29,
    name: "Phoe Japan Agency",
    type: "Agency",
    language: "WordPress",
    link: "https://www.phoejapanagency.com/",
    buttonText: "Visit",
  },
  {
    project_id: 30,
    name: "Ever Sunny Food",
    type: "Food",
    language: "WordPress",
    link: "https://www.eversunnyfood.com/",
    buttonText: "Visit",
  },
  {
    project_id: 31,
    name: "New Tomtai",
    type: "Marine",
    language: "WordPress",
    link: "https://www.newtomtai.com/",
    buttonText: "Visit",
  },
  {
    project_id: 32,
    name: "INNWA IT & Mobile",
    type: "IT & Mobile Sales & Services",
    language: "Laravel",
    link: "https://www.shop.innwa.com.mm/",
    buttonText: "Visit",
  },
  {
    project_id: 33,
    name: "Kevo Art",
    type: "Mural and Tattoo Artist",
    language: "WordPress",
    link: "https://www.kevoart.com/",
    buttonText: "Visit",
  },
  {
    project_id: 34,
    name: "Chery Myanmar",
    type: "Auto",
    language: "WordPress",
    link: "https://www.cherymyanmar.com/",
    buttonText: "Visit",
  },
  {
    project_id: 35,
    name: "My Home Land Services",
    type: "Security",
    language: "WordPress",
    link: "https://www.myhomelandservices.com/",
    buttonText: "Visit",
  },
  {
    project_id: 36,
    name: "Parami Tea",
    type: "Tea Products & Exporter",
    language: "WordPress",
    link: "https://www.paramitea.com/",
    buttonText: "Visit",
  },
  {
    project_id: 37,
    name: "Ozone",
    type: "Lubricants",
    language: "WordPress",
    link: "https://www.ozonelubricants.com/",
    buttonText: "Visit",
  },
  {
    project_id: 38,
    name: "Helix University College",
    type: "University",
    language: "WordPress",
    link: "https://www.helixuniversitycollege.com/",
    buttonText: "Visit",
  },
  {
    project_id: 39,
    name: "Ministry of Planning and Finance",
    type: "Planning and Finance",
    language: "Laravel",
    link: "https://www.frd.gov.mm/",
    buttonText: "Visit",
  },
  {
    project_id: 40,
    name: "Dai-ichi Life Insurance",
    type: "Insurance",
    language: "WordPress",
    link: "https://www.dai-ichi-life.com.mm/",
    buttonText: "Visit",
  },
  {
    project_id: 41,
    name: "Genius Education Group",
    type: "School",
    language: "WordPress",
    link: "https://www.geniusedugroup.com/",
    buttonText: "Visit",
  },
  {
    project_id: 42,
    name: "Kachin Corruption Prevention Unit",
    type: "Corruption Prevention Unit",
    language: "Laravel",
    link: "https://www.cpu-kachin.gov.mm/",
    buttonText: "Visit",
  },
  {
    project_id: 43,
    name: "Windward Marine Myanmar",
    type: "Marine Services",
    language: "WordPress",
    link: "https://www.windwardmarinemyanmar.com/",
    buttonText: "Visit",
  },
  {
    project_id: 44,
    name: "Best Secret Services",
    type: "Laptop Spare Parts Sales & Services",
    language: "WordPress",
    link: "https://www.bestsecretservices.com/",
    buttonText: "Visit",
  },
  {
    project_id: 45,
    name: "Shwe San Nann",
    type: "Construction",
    language: "WordPress",
    link: "https://www.shwesannann.com/",
    buttonText: "Visit",
  },
  {
    project_id: 46,
    name: "Phademic Myanmar",
    type: "Medical Products",
    language: "WordPress",
    link: "https://www.phamedicmyanmar.com/",
    buttonText: "Visit",
  },
  {
    project_id: 47,
    name: "HTDC",
    type: "Beauty Products",
    language: "WordPress",
    link: "https://www.yoon.skin.com.mm/",
    buttonText: "Visit",
  },
  {
    project_id: 48,
    name: "Smart Beauty",
    type: "Beauty Products",
    language: "WordPress",
    link: "https://www.smartbeauty.com.mm/",
    buttonText: "Visit",
  },
  {
    project_id: 49,
    name: "Lotaya Care",
    type: "Medical Products",
    language: "WordPress",
    link: "https://www.lotayacare.com/",
    buttonText: "Visit",
  },
  {
    project_id: 50,
    name: "Dr.H",
    type: "Beauty Products",
    language: "WordPress",
    link: "https://www.drhbeauty.us/",
    buttonText: "Visit",
  },
  {
    project_id: 51,
    name: "Bio Tica",
    type: "Beauty Products",
    language: "WordPress",
    link: "https://www.bioticabeauty.us/",
    buttonText: "Visit",
  },
];
export default WebProjectsData;
