const GraphicDesignProjectsData_FEB_2024 = [
  {
    project_id: 1,
    name: "Domain .com",
    image: "/projects/graphic_design/FEB/domain-.com.webp",
    alt: "Domain .com",
    campaign: "FEB 2024",
  },
  {
    project_id: 2,
    name: "Domain .ltd",
    image: "/projects/graphic_design/FEB/domain-.ltd.webp",
    alt: "Domain .ltd",
    campaign: "FEB 2024",
  },
  {
    project_id: 3,
    name: "Domain .agency",
    image: "/projects/graphic_design/FEB/domain-.agency.webp",
    alt: "Domain .agency",
    campaign: "FEB 2024",
  },
  {
    project_id: 4,
    name: "Domain .io",
    image: "/projects/graphic_design/FEB/domain-.io.webp",
    alt: "Domain .io",
    campaign: "FEB 2024",
  },
  {
    project_id: 5,
    name: "Domain .co",
    image: "/projects/graphic_design/FEB/domain-.co.webp",
    alt: "Domain .co",
    campaign: "FEB 2024",
  },
  {
    project_id: 6,
    name: "Domain .cafe",
    image: "/projects/graphic_design/FEB/domain-.cafe.webp",
    alt: "Domain .cafe",
    campaign: "FEB 2024",
  },
  {
    project_id: 7,
    name: "Domain .net",
    image: "/projects/graphic_design/FEB/domain-.net.webp",
    alt: "Domain .net",
    campaign: "FEB 2024",
  },
  {
    project_id: 8,
    name: "Private Hosting",
    image: "/projects/graphic_design/FEB/private-hosting.webp",
    alt: "Private Hosting",
    campaign: "FEB 2024",
  },
  {
    project_id: 9,
    name: "Website Service 01",
    image: "/projects/graphic_design/FEB/website-service-01.webp",
    alt: "Website Service 01",
    campaign: "FEB 2024",
  },
  {
    project_id: 10,
    name: "Website Service 02",
    image: "/projects/graphic_design/FEB/website-service-02.webp",
    alt: "Website Service 02",
    campaign: "FEB 2024",
  },
  {
    project_id: 11,
    name: "Website",
    image: "/projects/graphic_design/FEB/website.webp",
    alt: "Website",
    campaign: "FEB 2024",
  },
  {
    project_id: 12,
    name: "Dragon Sale",
    image: "/projects/graphic_design/FEB/dragon-sale.webp",
    alt: "Dragon Sale",
    campaign: "FEB 2024",
  },
  {
    project_id: 13,
    name: "Special Offer",
    image: "/projects/graphic_design/FEB/special-offer.webp",
    alt: "Special Offer",
    campaign: "FEB 2024",
  },
];
export default GraphicDesignProjectsData_FEB_2024;
