const GraphicDesignProjectsData_MAR_2024 = [
  {
    project_id: 1,
    name: "Private Hosting 01",
    image: "/projects/graphic_design/MAR/private-hosting-01.webp",
    alt: "Private Hosting 01",
    campaign: "MAR 2024",
  },
  {
    project_id: 2,
    name: "Private Hosting 02",
    image: "/projects/graphic_design/MAR/private-hosting-02.webp",
    alt: "Private Hosting 02",
    campaign: "MAR 2024",
  },
  {
    project_id: 3,
    name: "WordPress Hosting 01",
    image: "/projects/graphic_design/MAR/wordpress-hosting-01.webp",
    alt: "WordPress Hosting 01",
    campaign: "MAR 2024",
  },
  {
    project_id: 4,
    name: "WordPress Hosting 02",
    image: "/projects/graphic_design/MAR/wordpress-hosting-02.webp",
    alt: "WordPress Hosting 02",
    campaign: "MAR 2024",
  },
  {
    project_id: 5,
    name: "Website Development",
    image: "/projects/graphic_design/MAR/website-development.webp",
    alt: "Website Development",
    campaign: "MAR 2024",
  },
  {
    project_id: 6,
    name: "Email Hosting 01",
    image: "/projects/graphic_design/MAR/email-hosting-01.webp",
    alt: "Email Hosting 01",
    campaign: "MAR 2024",
  },
  {
    project_id: 7,
    name: "Email Hosting 02",
    image: "/projects/graphic_design/MAR/email-hosting-02.webp",
    alt: "Email Hosting 02",
    campaign: "MAR 2024",
  },
  {
    project_id: 8,
    name: "Shopup",
    image: "/projects/graphic_design/MAR/shopup.webp",
    alt: "Shopup",
    campaign: "MAR 2024",
  },
  {
    project_id: 9,
    name: "Knowledge",
    image: "/projects/graphic_design/MAR/knowledge.webp",
    alt: "Knowledge",
    campaign: "MAR 2024",
  },
  {
    project_id: 10,
    name: "Domain .com",
    image: "/projects/graphic_design/MAR/domain-.com.webp",
    alt: "Domain .com",
    campaign: "MAR 2024",
  },
  {
    project_id: 11,
    name: "Domain .org",
    image: "/projects/graphic_design/MAR/domain-.org.webp",
    alt: "Domain .org",
    campaign: "MAR 2024",
  },
  {
    project_id: 12,
    name: "Domain .dev",
    image: "/projects/graphic_design/MAR/domain-.dev.webp",
    alt: "Domain .dev",
    campaign: "MAR 2024",
  },
  {
    project_id: 13,
    name: "Domain .app",
    image: "/projects/graphic_design/MAR/domain-.app.webp",
    alt: "Domain .app",
    campaign: "MAR 2024",
  },
  {
    project_id: 14,
    name: "Domain .wtf",
    image: "/projects/graphic_design/MAR/domain-.wtf.webp",
    alt: "Domain .wtf",
    campaign: "MAR 2024",
  },
  {
    project_id: 15,
    name: "Web Development Service",
    image: "/projects/graphic_design/MAR/web-development-service.webp",
    alt: "Web Development Service",
    campaign: "MAR 2024",
  },
  {
    project_id: 16,
    name: "Give Away",
    image: "/projects/graphic_design/MAR/give-away.webp",
    alt: "Give Away",
    campaign: "MAR 2024",
  },
  {
    project_id: 17,
    name: "Summer Sale",
    image: "/projects/graphic_design/MAR/summer-sale.webp",
    alt: "Summer Sale",
    campaign: "MAR 2024",
  },
  {
    project_id: 18,
    name: "Special Offer",
    image: "/projects/graphic_design/MAR/special-offer.webp",
    alt: "Special Offer",
    campaign: "MAR 2024",
  },
];
export default GraphicDesignProjectsData_MAR_2024;
