const Data = [
  {
    id: 1,
    name: "Ubuntu",
    type: "Operating System",
    image: "/logo/server/ubuntu.webp",
    alt: "Ubuntu Logo",
  },
  {
    id: 2,
    name: "WHM",
    type: "Web Host Manager",
    image: "/logo/server/whm.webp",
    alt: "WHM Logo",
  },
  {
    id: 3,
    name: "cPanel",
    type: "Web Control Panel",
    image: "/logo/server/cpanel.webp",
    alt: "cPanel Logo",
  },
  {
    id: 4,
    name: "Plesk",
    type: "Web Control Panel",
    image: "/logo/server/plesk.webp",
    alt: "Plesk Logo",
  },
  {
    id: 5,
    name: "DirectAdmin",
    type: "Web Control Panel",
    image: "/logo/server/direct-admin.webp",
    alt: "DirectAdmin Logo",
  },
  {
    id: 6,
    name: "NGINX",
    type: "Web Server",
    image: "/logo/server/nginx.webp",
    alt: "NGINX Logo",
  },
  {
    id: 7,
    name: "XAMPP",
    type: "Local Cross-Platform Server",
    image: "/logo/server/xampp.webp",
    alt: "XAMPP Logo",
  },
  {
    id: 8,
    name: "WAMP",
    type: "Local Window Server",
    image: "/logo/server/wamp.webp",
    alt: "WAMP Logo",
  },
  {
    id: 9,
    name: "Cron Job",
    type: "Job Scheduler",
    image: "/logo/server/cron-job.webp",
    alt: "Cron Job Logo",
  },
  {
    id: 10,
    name: "Installatron",
    type: "Application Installer",
    image: "/logo/server/installatron.webp",
    alt: "Installatron Logo",
  },
  {
    id: 11,
    name: "Imunify 360",
    type: "Security",
    image: "/logo/server/imunify-360.webp",
    alt: "Imunify 360 Logo",
  },
  {
    id: 12,
    name: "Imunify AV",
    type: "Security",
    image: "/logo/server/imunify-av.webp",
    alt: "Imunify AV Logo",
  },
];
export default Data;
